trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  SrcFolder: 'src'
  StorageAccountName: 'StorageAccountName'
  npm_config_cache: $(Pipeline.Workspace)/.npm
  FolderPrefix: $(Build.SourceBranchName)

jobs:
- job: Publish_Storybook_to_Static_Site
  steps:
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | $(SrcFolder)/package-lock.json'
      restoreKeys: |
          npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Cache npm

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'ci'
      workingDir: '$(SrcFolder)'
    displayName: 'npm ci'
      
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '$(SrcFolder)'
      customCommand: 'run build-storybook'
    displayName: 'Build Storybook'

  - task: AzureFileCopy@3
    displayName: 'AzureBlob File Copy'
    inputs:
      SourcePath: '$(SrcFolder)/storybook-static'
      azureSubscription: 'ServiceConnection_Name'
      Destination: AzureBlob
      storage: $(StorageAccountName)
      ContainerName: '$web'
      BlobPrefix: $(FolderPrefix)